package main.java;

import com.intellij.openapi.components.ServiceManager;

import javax.swing.*;

public class TokenSettingsGUI  {
    private JPanel rootPanel;
    private JTextField tokenText;
    private JButton testButton;
    private JTextArea testText;
    private JLabel label;
    private boolean tokenIsGood = false;
    final StaticComponents stat = StaticComponents.getInstance();

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    TokenSettingsGUI() {
        createUIComponents();
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    public JTextField getTextField1() {
        return tokenText;
    }
    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
//        rootPanel = new JPanel();
//       rootPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
//        rootPanel.setRequestFocusEnabled(true);
//        rootPanel.add(textField1);

    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    private void createUIComponents() {
        tokenIsGood = true;
        if(stat.getToken()!=null){
            tokenText.setText(stat.getToken());
        }
        testButton.addActionListener(e -> {
            if(tokenIsGood) {
                testText.setText("Красава");
                stat.setToken(tokenText.getText());
            }
        });
    }

}
